<?php

/**
 * Account
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * Account
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Account implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "creditLine" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "readOnly" : true,
      "example" : 120002
    },
    "accountType" : {
      "type" : "string",
      "example" : "creditCard",
      "enum" : [ "checking", "timeDeposit", "creditCard" ]
    },
    "name" : {
      "type" : "string",
      "example" : "Student Zero Plus",
      "enum" : [ "Student Zero Plus", "The Free Account", "Business-Card Gold" ]
    },
    "credit" : {
      "type" : "number",
      "format" : "currency"
    },
    "PIN" : {
      "type" : "string",
      "format" : "password",
      "writeOnly" : true,
      "example" : "434343"
    },
    "creditLine" : {
      "type" : "number",
      "format" : "currency"
    },
    "interest" : {
      "type" : "number",
      "format" : "float"
    },
    "reference" : {
      "type" : "integer",
      "description" : "if this is a credit-card-account then reference is a ref to a checking account",
      "format" : "int64",
      "nullable" : true,
      "example" : 120001
    },
    "users" : {
      "type" : "array",
      "description" : "ids of users who manage this account",
      "readOnly" : true,
      "items" : {
        "type" : "integer",
        "format" : "int64"
      }
    }
  }
}
SCHEMA;

    /** @var int $id */
    private $id;

    /** @var string $accountType */
    private $accountType;

    /** @var string $name */
    private $name;

    /** @var float $credit */
    private $credit;

    /** @var string $pIN */
    private $pIN;

    /** @var float $creditLine */
    private $creditLine;

    /** @var float $interest */
    private $interest;

    /** @var int $reference if this is a credit-card-account then reference is a ref to a checking account*/
    private $reference;

    /** @var int[] $users ids of users who manage this account*/
    private $users;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
