<?php

/**
 * Transaction
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * Transaction
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Transaction implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "account", "amount", "user" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "user" : {
      "type" : "integer",
      "description" : "id of the user",
      "format" : "int64",
      "example" : 6800012345
    },
    "account" : {
      "type" : "integer",
      "description" : "id of the account",
      "format" : "int64",
      "example" : 120002
    },
    "amount" : {
      "type" : "number",
      "format" : "currency"
    },
    "date" : {
      "type" : "string",
      "format" : "date",
      "readOnly" : true,
      "example" : "2020-03-16"
    }
  }
}
SCHEMA;

    /** @var int $id */
    private $id;

    /** @var int $user id of the user*/
    private $user;

    /** @var int $account id of the account*/
    private $account;

    /** @var float $amount */
    private $amount;

    /** @var \DateTime $date */
    private $date;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
