<?php

/**
 * User
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * User
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class User implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "dateOfBirth", "firstName", "surname" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "readOnly" : true,
      "example" : 6800012345
    },
    "surname" : {
      "type" : "string",
      "example" : "Mustermann"
    },
    "firstName" : {
      "type" : "string",
      "example" : "Max"
    },
    "dateOfBirth" : {
      "type" : "string",
      "format" : "date",
      "example" : "1991-09-19"
    },
    "sex" : {
      "type" : "string",
      "example" : "M"
    },
    "accounts" : {
      "type" : "array",
      "readOnly" : true,
      "items" : {
        "type" : "integer",
        "description" : "the key to a user, who has rights",
        "format" : "int64"
      }
    }
  }
}
SCHEMA;

    /** @var int $id */
    private $id;

    /** @var string $surname */
    private $surname;

    /** @var string $firstName */
    private $firstName;

    /** @var \DateTime $dateOfBirth */
    private $dateOfBirth;

    /** @var string $sex */
    private $sex;

    /** @var int[] $accounts */
    private $accounts;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
