<?php

/**
 * AdvisorsApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Bank Backend API
 *
 * Bank Backend API
 * The version of the OpenAPI document: 1.1
 * Contact: mail@axelganter.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\AdvisorsApi;

/**
 * AdvisorsApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\AdvisorsApi
 */
class AdvisorsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getUser
     *
     * Get a user by ID.
     *
     * @covers ::getUser
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for newAccount
     *
     * add new account.
     *
     * @covers ::newAccount
     */
    public function testNewAccount()
    {
    }

    /**
     * Test case for newUser
     *
     * add new user.
     *
     * @covers ::newUser
     */
    public function testNewUser()
    {
    }
}
